on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*.*.*' # Push events to matching v*, i.e. v1.0, v20.15.10
  
name: Create Release

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:

      - name: Set up go cache
        uses: actions/cache@v2
        with:
          path: ~/go
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Unshallow
        run: git fetch --prune --unshallow
      -
        name: Set up Go 1.15.x
        uses: actions/setup-go@v1
        with:
          go-version: 1.15.x
      
      -
        name: Dependencies
        run: |
          export PATH=$(go env GOPATH)/bin:$PATH
          make depsdev deps
          git checkout go.mod go.sum

      -
        name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export PATH=$(go env GOPATH)/bin:$PATH
          make release_publish






















